- hosts: wordpress
  become: true
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  gather_facts: true
  vars:
    - server_hostname: www.milevsky.quest
    - wp_version: 4.7.5
    - wp_sha1sum: fbe0ee1d9010265be200fe50b86f341587187302
    - wp_db_name: wordpress
    - wp_db_user: wordpress
    - wp_db_password: wordpress
    - auto_up_disable: true
    - core_update_level: true
    - wp_db_host: db01.milevsky.quest
  roles:
    - nginx
    - php
    - wordpress
