- hosts: wordpress
  become: true
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  gather_facts: true
  vars:
    - domain: "www.milevsky.quest"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
  roles:
    - nginx
    - php
    - wordpress
